import type { BookSource } from "./types";

/**
 * Curated book manifest for Sonata term extraction.
 *
 * Every entry maps to a real Internet Archive (or Google Books) item so that
 * the pipeline can fetch genuine fulltext and produce real, citable source
 * records. `freeTextKnown` records whether the fulltext is openly downloadable
 * today; the fetcher will probe at runtime regardless, so the flag is only a
 * convenience hint for the review report.
 *
 * NOTE on rights: many classic scholarly books on Internet Archive are
 * lending-library items (Access-restricted-item). Those must be handled under
 * IA's lending terms and should be kept alongside a legal path. The pipeline
 * reports which books are freely downloadable so the operator can decide which
 * set to author. We deliberately prefer public-domain / CC / open items where
 * possible.
 */
export const BOOKS: BookSource[] = [
  // ------------------------------------------------------------------
  // South Asia
  // ------------------------------------------------------------------
  {
    region: "south-asia",
    slug: "sambamoorthy-history-indian-music",
    title: "History of Indian Music",
    author: "P. Sambamoorthy",
    year: "1960",
    kind: "internet-archive",
    identifier: "HistoryOfIndianMusicBySambamoorthy",
    publisher: "The Indian Music Publishing House, Madras",
    citation: "Sambamoorthy, P. History of Indian Music. The Indian Music Publishing House, Madras, 1960.",
    freeTextKnown: true,
  },
  {
    region: "south-asia",
    slug: "popley-music-of-india",
    title: "The Music of India",
    author: "Herbert A. Popley",
    year: "1921",
    kind: "internet-archive",
    identifier: "musicofindia00popl",
    publisher: "Association Press, Calcutta; Oxford University Press",
    citation: "Popley, Herbert A. The Music of India. Association Press, Calcutta; Oxford University Press, 1921.",
    freeTextKnown: true,
  },
  {
    region: "south-asia",
    slug: "fyzeerahamin-indian-music",
    title: "Indian Music",
    author: "Atiya Begum Fyzee Rahamin",
    year: "1914",
    kind: "internet-archive",
    identifier: "cu31924022492338",
    publisher: "W. Marchant & Co., London",
    citation: "Fyzee Rahamin, Atiya Begum. Indian Music. W. Marchant & Co., London, 1914.",
    freeTextKnown: true,
  },
  {
    region: "south-asia",
    slug: "telang-22-shrutis",
    title: "The 22 Shrutis of Indian Music",
    author: "Mangesh R. Telang",
    year: "1933",
    kind: "internet-archive",
    identifier: "1933-m-r-telang-the-22-srutis-of-indian-music",
    citation: "Telang, Mangesh R. The 22 Shrutis of Indian Music. 1933.",
    freeTextKnown: true,
  },
  {
    region: "south-asia",
    slug: "jairazbhoy-rags-north-indian",
    title: "The Rāgs of North Indian Music",
    author: "Nazir Ali Jairazbhoy",
    year: "1971",
    kind: "internet-archive",
    identifier: "ragsofnorthindia00jair",
    citation: "Jairazbhoy, Nazir Ali. The Rāgs of North Indian Music: Their Structure and Evolution. Wesleyan University Press, 1971.",
    freeTextKnown: false,
  },
  {
    region: "south-asia",
    slug: "kaufmann-ragas-north-india",
    title: "The Ragas of North India",
    author: "Walter Kaufmann",
    year: "1968",
    kind: "internet-archive",
    identifier: "ragasofnorthindi0000kauf",
    citation: "Kaufmann, Walter. The Ragas of North India. Indiana University Press, 1968.",
    freeTextKnown: false,
  },
  {
    region: "south-asia",
    slug: "gautam-evolution-raga-tala",
    title: "Evolution of Rāga and Tāla in Indian Music",
    author: "M. R. Gautam",
    year: "1993",
    kind: "internet-archive",
    identifier: "evolutionofragat0000gaut",
    citation: "Gautam, M. R. Evolution of Rāga and Tāla in Indian Music. Munshiram Manoharlal, 1993.",
    freeTextKnown: false,
  },
  {
    region: "south-asia",
    slug: "day-music-southern-india-deccan",
    title: "The Music and Musical Instruments of Southern India and the Deccan",
    author: "C. R. Day",
    year: "1891",
    kind: "internet-archive",
    identifier: "musicmusicalinst00dayc",
    publisher: "Novello, Ewer & Co., London",
    citation: "Day, C. R. The Music and Musical Instruments of Southern India and the Deccan. Novello, Ewer & Co., London, 1891.",
    freeTextKnown: true,
  },

  // ------------------------------------------------------------------
  // Middle East
  // ------------------------------------------------------------------
  {
    region: "middle-east",
    slug: "farmer-history-arabian-music",
    title: "A History of Arabian Music",
    author: "Henry George Farmer",
    year: "1929",
    kind: "internet-archive",
    identifier: "historyofarabian030364mbp",
    publisher: "Luzac & Co., London",
    citation: "Farmer, Henry George. A History of Arabian Music. Luzac & Co., London, 1929.",
    freeTextKnown: true,
  },
  {
    region: "middle-east",
    slug: "touma-music-arabs",
    title: "The Music of the Arabs",
    author: "Habib Hassan Touma",
    year: "1996",
    kind: "internet-archive",
    identifier: "musicofarabs0000toum",
    citation: "Touma, Habib Hassan. The Music of the Arabs. Amadeus Press, 1996.",
    freeTextKnown: false,
  },
  {
    region: "middle-east",
    slug: "farmad-al-adwar",
    title: "Kitāb al-Adwār fī al-mūsīqā",
    author: "Safi al-Din al-Urmawi",
    year: "c. 1250",
    kind: "internet-archive",
    identifier: "ljs235",
    citation: "Urmawī, ʻAbd al-Muʼmin ibn Yūsuf. Kitāb al-Adwār fī al-mūsīqā. Manuscript, University of Pennsylvania (LJS 235).",
    freeTextKnown: true,
  },

  // ------------------------------------------------------------------
  // Central Asia (freely-downloadable public domain)
  // ------------------------------------------------------------------
  {
    region: "central-asia",
    slug: "skrine-heart-of-asia",
    title: "The Heart of Asia: A History of Russian Turkestan and the Central Asian Khanates",
    author: "Francis Henry Skrine; E. Denison Ross",
    year: "1899",
    kind: "internet-archive",
    identifier: "heartofasiahisto00skriuoft",
    publisher: "Methuen, London",
    citation: "Skrine, Francis Henry, and E. Denison Ross. The Heart of Asia: A History of Russian Turkestan and the Central Asian Khanates. Methuen, London, 1899.",
    freeTextKnown: true,
  },
  {
    region: "central-asia",
    slug: "meakin-in-russian-turkestan",
    title: "In Russian Turkestan: A Garden of Asia and Its People",
    author: "Annette M. B. Meakin",
    year: "1903",
    kind: "internet-archive",
    identifier: "inrussianturkes00meakgoog",
    publisher: "G. Allen, London",
    citation: "Meakin, Annette M. B. In Russian Turkestan: A Garden of Asia and Its People. G. Allen, London, 1903.",
    freeTextKnown: true,
  },

  // ------------------------------------------------------------------
  // North Africa (freely-downloadable public domain)
  // ------------------------------------------------------------------
  {
    region: "north-africa",
    slug: "rae-country-of-the-moors",
    title: "The Country of the Moors: A Journey from Tripoli to the City of Kairwân",
    author: "Edward Rae",
    year: "1877",
    kind: "internet-archive",
    identifier: "countryofmoorsjo00raeeiala",
    publisher: "John Murray, London",
    citation: "Rae, Edward. The Country of the Moors: A Journey from Tripoli to the City of Kairwân. John Murray, London, 1877.",
    freeTextKnown: true,
  },
  {
    region: "north-africa",
    slug: "bonsal-morocco-as-it-is",
    title: "Morocco as It Is",
    author: "Stephen Bonsal",
    year: "1893",
    kind: "internet-archive",
    identifier: "moroccoasitiswit00bons",
    publisher: "Harper & Brothers, New York",
    citation: "Bonsal, Stephen. Morocco as It Is. Harper & Brothers, New York, 1893.",
    freeTextKnown: true,
  },

  // ------------------------------------------------------------------
  // East Asia
  // ------------------------------------------------------------------
  {
    region: "east-asia",
    slug: "sancai-tuhui-instruments",
    title: "Sancai Tuhui (Collected Illustrations of the Three Realms), Vol. 45",
    author: "Wang Qi, Wang Siyi",
    year: "1609",
    kind: "internet-archive",
    identifier: "02095031.cn",
    citation: "Wang Qi and Wang Siyi. Sancai Tuhui, Vol. 45 (Musical Instruments). 1609. Peking University Library digitization.",
    freeTextKnown: true,
  },
  {
    region: "east-asia",
    slug: "levis-foundations-chinese",
    title: "Foundations of Chinese Musical Art",
    author: "John Hazedel Levis",
    year: "1964",
    kind: "internet-archive",
    identifier: "foundationsofchi0000levi",
    citation: "Levis, John Hazedel. Foundations of Chinese Musical Art. Paragon Book Reprint Corp., 1964.",
    freeTextKnown: false,
  },

  // ------------------------------------------------------------------
  // Southeast Asia
  // ------------------------------------------------------------------
  {
    region: "southeast-asia",
    slug: "kunst-hindu-javanese-instruments",
    title: "Hindu-Javanese Musical Instruments",
    author: "Jaap Kunst",
    year: "1927",
    kind: "internet-archive",
    identifier: "hindujavanesemus0000jaap",
    publisher: "Martinus Nijhoff, The Hague",
    citation: "Kunst, Jaap. Hindu-Javanese Musical Instruments. Martinus Nijhoff, The Hague, 1927.",
    freeTextKnown: true,
  },
  {
    region: "southeast-asia",
    slug: "kunst-music-in-java",
    title: "Music in Java: Its History, Its Theory, and Its Technique",
    author: "Jaap Kunst",
    year: "1973",
    kind: "internet-archive",
    identifier: "musicinjavaitshi0001kuns",
    citation: "Kunst, Jaap. Music in Java: Its History, Its Theory, and Its Technique. Martinus Nijhoff, The Hague, 1973.",
    freeTextKnown: false,
  },

  // ------------------------------------------------------------------
  // Sub-Saharan Africa
  // ------------------------------------------------------------------
  {
    region: "sub-saharan-africa",
    slug: "nketia-music-of-africa",
    title: "The Music of Africa",
    author: "J. H. Kwabena Nketia",
    year: "1974",
    kind: "internet-archive",
    identifier: "musicofafrica000nket",
    citation: "Nketia, J. H. Kwabena. The Music of Africa. W. W. Norton, 1974.",
    freeTextKnown: false,
  },
  {
    region: "sub-saharan-africa",
    slug: "jones-studies-african-music",
    title: "Studies in African Music",
    author: "A. M. Jones",
    year: "1959",
    kind: "internet-archive",
    identifier: "studiesinamerica0000unse_a8p5",
    citation: "Jones, A. M. Studies in African Music. Oxford University Press, 1959.",
    freeTextKnown: false,
  },
  {
    region: "sub-saharan-africa",
    slug: "bebey-african-music-people-art",
    title: "African Music: A People's Art",
    author: "Francis Bebey",
    year: "1975",
    kind: "internet-archive",
    identifier: "africanmusicpeop00bebe",
    citation: "Bebey, Francis. African Music: A People's Art. Lawrence Hill, 1975.",
    freeTextKnown: false,
  },
  {
    region: "sub-saharan-africa",
    slug: "lugard-tropical-dependency",
    title: "A Tropical Dependency: An Outline of the Ancient History of the Western Sudan",
    author: "Flora Louise Shaw Lugard",
    year: "1905",
    kind: "internet-archive",
    identifier: "tropicaldependen00luga",
    publisher: "James Nisbet, London",
    citation: "Lugard, Flora Louise Shaw. A Tropical Dependency: An Outline of the Ancient History of the Western Sudan. James Nisbet, London, 1905.",
    freeTextKnown: true,
    note: "Western Sudan / northern Nigeria historical travel; includes accounts of music, drumming, and song in regional ceremony.",
  },

  // ------------------------------------------------------------------
  // Europe
  // ------------------------------------------------------------------
  {
    region: "europe",
    slug: "sachs-history-musical-instruments",
    title: "The History of Musical Instruments",
    author: "Curt Sachs",
    year: "1940",
    kind: "internet-archive",
    identifier: "historyofmusical0000unse_k1p8",
    citation: "Sachs, Curt. The History of Musical Instruments. W. W. Norton, 1940.",
    freeTextKnown: false,
  },
  {
    region: "europe",
    slug: "engel-south-kensington-instruments",
    title: "A Descriptive Catalogue of the Musical Instruments in the South Kensington Museum",
    author: "Carl Engel",
    year: "1874",
    kind: "internet-archive",
    identifier: "adescriptivecat00engegoog",
    publisher: "George E. Eyre and William Spottiswoode, London",
    citation: "Engel, Carl. A Descriptive Catalogue of the Musical Instruments in the South Kensington Museum. George E. Eyre and William Spottiswoode, London, 1874.",
    freeTextKnown: true,
    note: "European instruments with cross-regional (Eastern, African, American) comparisons.",
  },
  {
    region: "europe",
    slug: "brown-musical-instruments-and-their-homes",
    title: "Musical Instruments and Their Homes",
    author: "Mary E. Brown; Wm. Adams Brown",
    year: "1888",
    kind: "internet-archive",
    identifier: "cu31924022445849",
    publisher: "Dodd, Mead and Company, New York",
    citation: "Brown, Mary E., and Wm. Adams Brown. Musical Instruments and Their Homes. Dodd, Mead and Company, New York, 1888.",
    freeTextKnown: true,
    note: "Global catalogue of European and non-European (Oriental, African) instruments.",
  },
  {
    region: "europe",
    slug: "farmer-new-oxford-volume",
    title: "European Music (reference selection)",
    author: "Various",
    year: "1954",
    kind: "google-books",
    volumeId: "",
    citation: "European music reference volume.",
    freeTextKnown: false,
  },

  // ------------------------------------------------------------------
  // Latin America
  // ------------------------------------------------------------------
  {
    region: "latin-america",
    slug: "stevenson-music-mexico",
    title: "Music in Mexico: A Historical Survey",
    author: "Robert Stevenson",
    year: "1952",
    kind: "internet-archive",
    identifier: "musicinmexicoahi007091mbp",
    publisher: "Thomas Y. Crowell",
    citation: "Stevenson, Robert. Music in Mexico: A Historical Survey. Thomas Y. Crowell, 1952.",
    freeTextKnown: true,
  },
  {
    region: "latin-america",
    slug: "slonimsky-music-latin-america",
    title: "Music of Latin America",
    author: "Nicolas Slonimsky",
    year: "1946",
    kind: "internet-archive",
    identifier: "MusicOfTheLatinAmerica",
    publisher: "Thomas Y. Crowell",
    citation: "Slonimsky, Nicolas. Music of Latin America. Thomas Y. Crowell, 1946.",
    freeTextKnown: true,
  },
  {
    region: "latin-america",
    slug: "slonimsky-music-latin-america-1945",
    title: "Music of Latin America",
    author: "Nicolas Slonimsky",
    year: "1945",
    kind: "internet-archive",
    identifier: "musicoflatinamer00slon",
    citation: "Slonimsky, Nicolas. Music of Latin America. Thomas Y. Crowell, 1945.",
    freeTextKnown: false,
  },

  // ------------------------------------------------------------------
  // East Asia (Japan / China)
  // ------------------------------------------------------------------
  {
    region: "east-asia",
    slug: "piggott-music-japan-1893",
    title: "The Music and Musical Instruments of Japan",
    author: "Francis Taylor Piggott",
    year: "1893",
    kind: "internet-archive",
    identifier: "musicandmusical00soutgoog",
    publisher: "B. T. Batsford, London",
    citation: "Piggott, Francis Taylor. The Music and Musical Instruments of Japan. B. T. Batsford, London, 1893.",
    freeTextKnown: true,
  },
  {
    region: "east-asia",
    slug: "malm-japanese-music",
    title: "Japanese Music and Musical Instruments",
    author: "William P. Malm",
    year: "1959",
    kind: "internet-archive",
    identifier: "japanesemusicmus00malm",
    citation: "Malm, William P. Japanese Music and Musical Instruments. C. E. Tuttle Co., 1959.",
    freeTextKnown: false,
  },
  {
    region: "east-asia",
    slug: "kishibe-traditional-music-japan",
    title: "The Traditional Music of Japan",
    author: "Shigeo Kishibe",
    year: "1969",
    kind: "internet-archive",
    identifier: "traditionalmusic00kish",
    citation: "Kishibe, Shigeo. The Traditional Music of Japan. Kokusai Bunka Shinkokai, 1969.",
    freeTextKnown: false,
  },

  // ------------------------------------------------------------------
  // North America
  // ------------------------------------------------------------------
  {
    region: "north-america",
    slug: "allen-slave-songs",
    title: "Slave Songs of the United States",
    author: "William Francis Allen, Charles Pickard Ware, Lucy McKim Garrison",
    year: "1867",
    kind: "internet-archive",
    identifier: "slavesongsofunit00alle",
    publisher: "A. Simpson & Co., New York",
    citation: "Allen, William Francis; Ware, Charles Pickard; Garrison, Lucy McKim. Slave Songs of the United States. A. Simpson & Co., New York, 1867.",
    freeTextKnown: true,
  },
  {
    region: "north-america",
    slug: "work-folk-song-american-negro",
    title: "Folk Song of the American Negro",
    author: "John Wesley Work",
    year: "1915",
    kind: "internet-archive",
    identifier: "folkameric00work",
    publisher: "Fisk University Press, Nashville",
    citation: "Work, John Wesley. Folk Song of the American Negro. Fisk University Press, Nashville, 1915.",
    freeTextKnown: true,
  },
  {
    region: "north-america",
    slug: "krehbiel-afro-american-folksongs",
    title: "Afro-American Folksongs",
    author: "Henry Edward Krehbiel",
    year: "1914",
    kind: "internet-archive",
    identifier: "afroamericanfolk00krehb",
    publisher: "G. Schirmer, New York",
    citation: "Krehbiel, Henry Edward. Afro-American Folksongs: A Study in Racial and National Music. G. Schirmer, New York, 1914.",
    freeTextKnown: false,
  },
  {
    region: "north-america",
    slug: "cable-creole-slave-songs",
    title: "Creole Slave Songs",
    author: "George Washington Cable",
    year: "1886",
    kind: "internet-archive",
    identifier: "creoleslavesongs00cabl",
    publisher: "The Century Co.",
    citation: "Cable, George Washington. Creole Slave Songs. The Century Co., 1886.",
    freeTextKnown: true,
  },

  // ------------------------------------------------------------------
  // Caribbean
  // ------------------------------------------------------------------
  {
    region: "caribbean",
    slug: "manuel-caribbean-currents",
    title: "Caribbean Currents: Caribbean Music from Rumba to Reggae",
    author: "Peter Manuel, Kenneth Bilby, Michael Largey",
    year: "1995",
    kind: "internet-archive",
    identifier: "caribbeancurrent00manu",
    citation: "Manuel, Peter; Bilby, Kenneth; Largey, Michael. Caribbean Currents: Caribbean Music from Rumba to Reggae. Temple University Press, 1995.",
    freeTextKnown: false,
  },
  {
    region: "caribbean",
    slug: "rohlehr-calypso-trinidad",
    title: "Calypso & Society in Pre-Independence Trinidad",
    author: "Gordon Rohlehr",
    year: "1990",
    kind: "internet-archive",
    identifier: "calypsosocietyin00rohl",
    citation: "Rohlehr, Gordon. Calypso & Society in Pre-Independence Trinidad. Port of Spain, 1990.",
    freeTextKnown: false,
  },
  {
    region: "caribbean",
    slug: "hill-calypso-calaloo",
    title: "Calypso Calaloo: Early Carnival Music in Trinidad",
    author: "Donald R. Hill",
    year: "1993",
    kind: "internet-archive",
    identifier: "calypsocalalooea00hill",
    citation: "Hill, Donald R. Calypso Calaloo: Early Carnival Music in Trinidad. University Press of Florida, 1993.",
    freeTextKnown: false,
  },
  {
    region: "caribbean",
    slug: "jekyll-jamaican-song-and-story",
    title: "Jamaican Song and Story: Annancy Stories, Digging Sings, Ring Tunes, and Dancing Tunes",
    author: "Walter Jekyll",
    year: "1907",
    kind: "internet-archive",
    identifier: "jamaicansongstor00jeky_0",
    publisher: "D. Nutt, London",
    citation: "Jekyll, Walter. Jamaican Song and Story: Annancy Stories, Digging Sings, Ring Tunes, and Dancing Tunes. D. Nutt, London, 1907.",
    freeTextKnown: true,
  },

  // ------------------------------------------------------------------
  // Southeast Asia (freely-downloadable)
  // ------------------------------------------------------------------
  {
    region: "southeast-asia",
    slug: "spiller-gamelan-indonesia",
    title: "Gamelan: The Traditional Sounds of Indonesia",
    author: "Henry Spiller",
    year: "2004",
    kind: "internet-archive",
    identifier: "GamelanTheTraditionalSoundsOfIndonesiaWorldMusic",
    publisher: "ABC-CLIO",
    citation: "Spiller, Henry. Gamelan: The Traditional Sounds of Indonesia. ABC-CLIO, 2004.",
    freeTextKnown: true,
  },

  // ------------------------------------------------------------------
  // Oceania (freely-downloadable public domain)
  // ------------------------------------------------------------------
  {
    region: "oceania",
    slug: "gill-myths-songs-south-pacific",
    title: "Myths and Songs from the South Pacific",
    author: "William Wyatt Gill",
    year: "1876",
    kind: "internet-archive",
    identifier: "mythssongsfromso00gill",
    publisher: "H. S. King, London",
    citation: "Gill, William Wyatt. Myths and Songs from the South Pacific. H. S. King, London, 1876.",
    freeTextKnown: true,
  },
  {
    region: "oceania",
    slug: "wallaschek-primitive-music",
    title: "Primitive Music",
    author: "Richard Wallaschek",
    year: "1893",
    kind: "internet-archive",
    identifier: "primitivemusicin00wall",
    publisher: "Longmans, Green, and Co.",
    citation: "Wallaschek, Richard. Primitive Music: An Inquiry into the Origin and Development of Music. Longmans, Green, and Co., 1893.",
    freeTextKnown: true,
    note: "Global / indigenous focus spanning Oceania, Africa, and the Americas.",
  },
  {
    region: "oceania",
    slug: "taylor-te-ika-a-maui",
    title: "Te Ika a Māui, or New Zealand and Its Inhabitants",
    author: "Richard Taylor",
    year: "1870",
    kind: "internet-archive",
    identifier: "teikamauiornewze00tayl",
    citation: "Taylor, Richard. Te Ika a Māui, or New Zealand and Its Inhabitants. 1870.",
    freeTextKnown: true,
  },

  // ------------------------------------------------------------------
  // Indigenous traditions globally (freely-downloadable public domain)
  // ------------------------------------------------------------------
  {
    region: "indigenous-traditions-globally",
    slug: "nettl-music-primitive-culture",
    title: "Music in Primitive Culture",
    author: "Bruno Nettl",
    year: "1956",
    kind: "internet-archive",
    identifier: "musicinprimitive0000nett_y7y5",
    citation: "Nettl, Bruno. Music in Primitive Culture. Harvard University Press, 1956.",
    freeTextKnown: false,
    note: "Indigenous/global focus; lending-only but central to cross-regional indigenous coverage.",
  },
  {
    region: "indigenous-traditions-globally",
    slug: "fletcher-omaha-indian-music",
    title: "A Study of Omaha Indian Music",
    author: "Alice C. Fletcher; Francis La Flesche; John Comfort Fillmore",
    year: "1893",
    kind: "internet-archive",
    identifier: "studyofomahaindi00flet",
    publisher: "Peabody Museum of American Archaeology and Ethnology, Harvard University",
    citation: "Fletcher, Alice C., with Francis La Flesche and John Comfort Fillmore. A Study of Omaha Indian Music. Peabody Museum, Harvard University, 1893.",
    freeTextKnown: true,
    note: "North American Indigenous (Omaha) song and ceremony; English OCR.",
  },
  {
    region: "indigenous-traditions-globally",
    slug: "curtis-burlin-indians-book",
    title: "The Indians' Book: Songs and Legends of the American Indians",
    author: "Natalie Curtis Burlin",
    year: "1907",
    kind: "internet-archive",
    identifier: "cu31924028767238",
    publisher: "Harper and Brothers, New York",
    citation: "Curtis Burlin, Natalie. The Indians' Book: An Offering of Songs and Legends of the American Indians. Harper and Brothers, New York, 1907.",
    freeTextKnown: true,
    note: "Multi-nation North American Indigenous song and ceremony; English OCR.",
  },
  {
    region: "indigenous-traditions-globally",
    slug: "gilman-hopi-songs",
    title: "Hopi Songs",
    author: "Benjamin Ives Gilman",
    year: "1908",
    kind: "internet-archive",
    identifier: "hopisongs00gilmuoft",
    publisher: "Houghton Mifflin, Boston",
    citation: "Gilman, Benjamin Ives. Hopi Songs. Houghton Mifflin, Boston, 1908.",
    freeTextKnown: true,
    note: "Hopi (Southwestern North American) song transcription and analysis; English OCR.",
  },
];
